### ISSUE TITLE
请问一下这个写法好还是每个组件中需要用到的组件一个个去import好

### ISSUE THREAD

**Issue by thewindear** [GitHubGanKai/vue3-jd-h5#11]
https://github.com/GitHubGanKai/vue3-jd-h5/blob/cbae5450b3893b6acb8c098f3a36f529199b4a43/src/components/index.js#L37

还是
```vue
import XXX from '~/components/XXX.vue'
```

**Comment by GitHubGanKai** [comment]
一般来说，如果一个组件只有一个文件中用到了他，那就直接在用到这个组件的文件中import就行，如果一个组件全局很多地方都有可能用到（比如tips，tabbar等），那就可以直接用这个方法！

**Comment by thewindear** [comment]
谢谢回答

**Comment by thewindear** [comment]
> 一般来说，如果一个组件只有一个文件中用到了他，那就直接在用到这个组件的文件中import就行，如果一个组件全局很多地方都有可能用到（比如tips，tabbar等），那就可以直接用这个方法！

多谢回答呵呵
