### ISSUE TITLE
请问是依赖于Python吗？

### ISSUE THREAD

**Issue by cn1001wang** [GitHubGanKai/vue3-jd-h5#12]
```
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
```

**Comment by GitHubGanKai** [comment]
你看下你的npm镜像是淘宝的还是其他的，估计你是在安装node_modules依赖的时候，node-sass安装失败！
你可以这样尝试：
1. 删除node_modules文件夹
2.运行 npm install --global windows-build-tools
3.使用npm重新安装node_modules或node-sass

**Comment by cn1001wang** [comment]
多谢反馈，我在网上也找到解决方法了；
[node-sass 安装失败的各种坑](https://www.jianshu.com/p/92afe92db99f)
全局安装
1. npm install -g node-gyp；
2.npm install --global --production windows-build-tools
然后就可以了
