### ISSUE TITLE
恕我眼拙，真没看出来是3.0

### ISSUE THREAD

**Issue by dushanyifenqing** [GitHubGanKai/vue3-jd-h5#13]
连setup到没看出来一个

**Comment by q134678123** [comment]
加2，我还以为是我玩李青玩太多了

**Comment by GitHubGanKai** [comment]
仔细看完文章后，再来发言！

**Comment by geekskai** [comment]
https://github.com/geekskai/vue3-jd-h5/blob/vue-next/src/src/views/home/index.vue
